### ISSUE TITLE
Packing order (`_perm` and `_scale_perm`)

### ISSUE THREAD

**Issue by fxmarty** [IST-DASLab/marlin#12]
Hi,

I am trying to understand the motivation for shuffling the scale/weight order: https://github.com/IST-DASLab/marlin/blob/3aa5a0534b453a47d81b724802f3561aa365085a/marlin/__init__.py#L125 & https://github.com/IST-DASLab/marlin/blob/3aa5a0534b453a47d81b724802f3561aa365085a/marlin/__init__.py#L133

We have `_scale_perm` being `[0, 8, 16, 24, 32, 40, 48, 56,,, 1, 9, 17, 25, 33, 41, 49, 57,,, 2, 10, 18, 26, 34, 42, 50, 58,,, ...]` up to 64, and `_perm = [0, 128, 8, 136, 16, 144, 24, 152,,, 256, 384, 264, 392, 272, 400, 280, 408, ...]` up to 1024.

At first I thought it might be related to the way data is owned by threads in `mma.sync.aligned.m16n8k16`, but I don't think it is related.

![image](https://github.com/IST-DASLab/marlin/assets/9808326/0da3f779-95c5-4472-813a-3ed9aedfd7ae)

Thank you!

**Comment by fxmarty** [comment]
cc @efrantar

**Comment by efrantar** [comment]
Yes, this is related to the tensor core layout.

Essentially we shuffle weights so that the `int4` value (16 bytes vector) which is read by each thread contains all 32 weights (in 4-bit) used by this thread in the corresponding 16x64 weight block (8 16x8 blocks as the left in your picture above). Additionally each `int` (4-byte) stores the 8 values corresponding to 2 16x8 blocks in the following interleaved binary format: `75316420` . This is so that we can efficiently unpack two "consecutive" weights, e.g. 0 and 1, directly into a `half2` in parallel.

All this shuffling is currently implemented by first "unrolling" all 16x16 blocks so that they are contiguous in memory and then applying the corresponding permutation to each consecutive 1024 elements (4 16x16 blocks that were unrolled). Here is the permutation generation with some comments:

```
for i in range(32): # for each thread in warp
    perm1 = []
    col = i // 4 # column in 16x8 TC block
    for block in [0, 1]: # 16x8 block in 16x16 super-block
        for row in [
            2 * (i % 4),
            2 * (i % 4) + 1,
            2 * (i % 4 + 4),
            2 * (i % 4 + 4) + 1
        ]: # 4 weights corresponding to thread in 16x8 block
            perm1.append(16 * row + col + 8 * block) # index in unrolled 16x16 block
    for j in range(4): # we have 4 unrolled 16x16 super-blocks consecutively
        perm.extend([p + 256 * j for p in perm1])
```

Scales are packed with a similar idea, each `int4` contains the 8 scales (one for each of the 8 16x8 blocks in the 16x64 tile) required by a thread corresponding to one of the 8 columns in a 16x8 tensor core block.

**Comment by fxmarty** [comment]
Thank you for taking the time to detail the process, it is much appreciated.

As I understand, we work on 16x64 weight blocks in the int4 world, which map to 8 16x8 weight blocks in the fp16 world, and thus 8 mma.sync calls. https://github.com/IST-DASLab/marlin/blob/3aa5a0534b453a47d81b724802f3561aa365085a/marlin/marlin_cuda_kernel.cu#L445-L458 The intuition for shuffling the weight matrix first is make it so that all the int4 data that will be used by a single thread in the 8 mma.sync operation is contiguous already in global memory.

> 16x8 blocks as the left in your picture above

The picture is slightly misleading (that is 8x8 on the picture with 32 bits data, but really 16x8 with 16 bits data), I think you are referring to the right (yellow) matrix, which corresponds to the b_frag. This aligns well with the row indexing you have
```
T0
T0
T1
T1
T2
T2
T3
T3
T0
T0
T1
T1
T2
T2
T3
T3
```

Concerning

> Additionally each int (4-byte) stores the 8 values corresponding to 2 16x8 blocks in the following interleaved binary format: 75316420 . This is so that we can efficiently unpack two "consecutive" weights, e.g. 0 and 1, directly into a half2 in parallel.

I don't follow, especially the second sentence, could you elaborate? I don't get how the `[0, 2, 4, 6, 1, 3, 5, 7]` reordering speeds up the int4 unpacking. I think [awq](https://github.com/mit-han-lab/llm-awq/blob/19a5a2c9db47f69a2851c83fea90f81ed49269ab/awq/quantize/qmodule.py#L93) used to do a similar reordering.

Additional question: does any of this relate to cutlass strategy to avoid bank conflicts in shared memory? Specifically referring to https://github.com/NVIDIA/cutlass/blob/main/media/docs/implicit_gemm_convolution.md#shared-memory-layouts. Are there strategies in the code to avoid bank conflicts?

**Comment by efrantar** [comment]
Yes, your understanding is correct; I meant the right matrix, operand B, where each element denotes a `half2`, i.e. 2 FP16 values. The reason we do this is because using the maximum vector-length (16 byte, i.e. one `int4` per thread in a warp) is ideal from a memory efficiency standpoint.

The idea of the sub-byte shuffling is that we eventually want to produce `half2`s (32-bit registers) containing consecutive FP16 weights. With some floating-point bit-hackery, it is possible to turn a quantized 4-bit value into its FP16 equivalent without performing expensive direct type conversions.

https://github.com/IST-DASLab/marlin/blob/3aa5a0534b453a47d81b724802f3561aa365085a/marlin/marlin_cuda_kernel.cu#L131

Since a GPU can multiply both FP16 values in a one `half2` with a single instruction, we can essentially do this bit-hacking conversion on two quantized values in parallel. This however requires that the two weights we want to decompress are in separate 16-bit parts of the 32-bit `int`; hence we perform this interleaving. AWQ indeed uses the same idea (although Marlin's conversion is slightly different since we force some LOP3 instructions and we do signed dequantization).

The above isn't directly related to bank conflicts; however, we also use as similar strategy as outlined in your link to avoid bank conflicts when writing and reading inputs (operand A) to/from shared memory, as 16-byte vectors; for the weights (operand B), there are no bank conflicts due to the preprocessing. We can however do some simplifications here as we have enough registers and also fully unroll the entire pipeline, allowing us to precompute all index remappings before the main loop (and hence we don't have to worry too much about the cost of this).

https://github.com/IST-DASLab/marlin/blob/3aa5a0534b453a47d81b724802f3561aa365085a/marlin/marlin_cuda_kernel.cu#L343

We also apply a padding trick for "unshuffling" the tensor core fragment layout without bank conflicts before the final write-out of results.

https://github.com/IST-DASLab/marlin/blob/3aa5a0534b453a47d81b724802f3561aa365085a/marlin/marlin_cuda_kernel.cu#L573

**Comment by fxmarty** [comment]
Thank you @efrantar for the detailed explanation. It is very helpful!
